src/Entity/Header.php
<?php

namespace App\Entity;

use App\Repository\HeaderRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HeaderRepository::class)
 */
class Header
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $btn_title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $btn_url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getBtnTitle(): ?string
    {
        return $this->btn_title;
    }

    public function setBtnTitle(string $btn_title): self
    {
        $this->btn_title = $btn_title;

        return $this;
    }

    public function getBtnUrl(): ?string
    {
        return $this->btn_url;
    }

    public function setBtnUrl(string $btn_url): self
    {
        $this->btn_url = $btn_url;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

templates/base.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="La boutique qui vend uniquement du made in France.">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <title>{% block title %}La Restaurant Tunisienne{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('assets/css/boutique.css') }}">

    {% block javascript %}
    {% endblock %}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{ asset('assets/css/carousel.css') }}" rel="stylesheet">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{{ path('home') }}">La Restaurant</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                {% if app.user %}
                <li class="nav-item active">
                    <a class="nav-link test" href="{{ path('menu_index') }}">Menus</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('items_index') }}">Items</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('meals_index') }}">Meals</a>
                </li>

               {% else %}
                <li class="nav-item active">
                    <a class="nav-link collapse navbar-collapse"  href="#Menu">Meillleurs Menus</a>
                </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#About"> About us</a>
                    </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#Items"> Meillleurs Items</a>
                </li>

{% endif %}
            </ul>
            <form class="form-inline my-2 my-lg-0 " style="    margin-right: 17px;" action="{{ path('recherche') }}" method="post">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="search" id="search">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
            <div class="nav-item-custom">
                {% if app.user %}
                    <a href="{{ path('account') }}">Mon compte <small>({{ app.user.firstname }})</small></a> | <a href="{{ path('app_logout') }}">Déconnexion</a>
                {% else %}
                    <a href="{{ path('app_login') }}">Connexion</a> | <a href="{{ path('app_register') }}">Inscription</a>
                {% endif %}
            </div>
{#            <a href="{{ path('mon-panier') }}">#}
{#                <img src="{{ asset('assets/img/shopping-cart.png') }}" class="cart-icon" alt="Mon panier">#}
{#            </a>#}
        </div>
    </nav>
</header>

<main role="main">

    {% if block('carousel') is defined %}
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for key,header in headers %}
                    <li data-target="#myCarousel" data-slide-to="{{ key }}" {% if key == 0 %}class="active"{% endif %}></li>
                {% endfor %}
            </ol>
            <div class="carousel-inner">
                {% for key,header in headers %}
                    <div class="carousel-item {% if key == 0 %}active{% endif %}" style="background: url('/uploads/files/{{ header.image }}');background-size:cover;">
                        <div class="container">
                            <div class="carousel-caption text-left">
                                <h1>{{ header.title }}</h1>
                                <p>{{ header.content }}</p>
                                <p><a class="btn btn-outline-primary" href="{{ header.btnUrl }}" role="button">{{ header.btnTitle }}</a></p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    {% endif %}

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing {% if block('carousel') is not defined %}mt-5{% endif %}">

        {% block body %}
        {% endblock %}

    </div><!-- /.container -->

    <!-- FOOTER -->
{#    <footer class="footer-custom">#}
{#        <p>#}
{#            &copy; 2020-2021 La Boutique Tunisienne<br/>#}
{#            <small>La boutique 100% made in Tunisia<br/>#}
{#                <a href="#">Privacy</a> &middot; <a href="#">Terms</a></small>#}
{#        </p>#}
{#    </footer>#}
</main>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="{{ asset('assets/js/bootstrap.bundle.js') }}"></script>
<script type="text/javascript">

    $('.test, .nav-link, .navbar-brand, .new-button').click(function() {
        var sectionTo = $(this).attr('href');
        $('html, body').animate({
            scrollTop: $(sectionTo).offset().top
        }, 1500);
    });
</script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


<script type="text/javascript">

    function placeFooter() {
        if( $(document.body).height() < $(window).height() ) {
            $("footer").css({position: "fixed", bottom:"0px"});
        } else {
            $("footer").css({position: ""});
        }
    }

    placeFooter();

</script>
</body>
{% block script %}
{% endblock %}
</html>