src/Entity/Menu.php
<?php

namespace App\Entity;

use App\Repository\MenuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=MenuRepository::class)
 */
class Menu
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @var \DateTime $created_at
     * @Gedmo\Timestampable (on="create")
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     *  @var \DateTime $updated_at
     *  @Gedmo\Timestampable (on="update")
     * @ORM\Column(type="datetime")
     */
    private $update_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="menus")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**

     * @ORM\Column(type="boolean",options={"default"=false}, nullable=true)
     */
    private $isBest;

    /**
     * @ORM\OneToMany(targetEntity=Items::class, mappedBy="menu")
     */
    private $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }
    public function __ToString(){

        return $this->getTitle();
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getIsBest(): ?bool
    {
        return $this->isBest;
    }

    public function setIsBest(bool $isBest): self
    {
        $this->isBest = $isBest;

        return $this;
    }

    /**
     * @return Collection|Items[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Items $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setMenu($this);
        }

        return $this;
    }

    public function removeItem(Items $item): self
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getMenu() === $this) {
                $item->setMenu(null);
            }
        }

        return $this;
    }
}

src/Controller/RechercheController.php
<?php

namespace App\Controller;

use App\Repository\ItemsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RechercheController extends AbstractController
{
    /**
     * @Route("/recherche", name="recherche")
     */
    public function index(Request $request, ItemsRepository $Item): Response
    {
        if ($request->getMethod() == "POST"){
            $shearch=$request->request->get("search");
              $go=  $Item->findItemByTitle($shearch);
        }
        return $this->render('recherche/index.html.twig', [
            'items' => $go,
        ]);
    }
}

templates/recherche/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Items index{% endblock %}

{% block body %}
    <h1>Recherche</h1>

    <a href="{{ path('items_new') }}" class="btn btn-outline-dark" style="float: right;margin-bottom: 22px;">Create new</a>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
            <th>Title</th>

            <th>Description</th>
            <th>Image</th>
            <th>Price</th>
            <th>Action</th>
            <th>CreatedBy</th>
        </tr>
        </thead>
        <tbody>
        {% for item in items %}
            <tr>


                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td><img src="/uploads/files/{{ item.image }}" height="100px"></td>
                <td>{{ item.price }}</td>
                <td>{{ item.User }}</td>
                {#                        <td>{{ menu.createdAt ? menu.createdAt|date('Y-m-d H:i:s') : '' }}</td>#}
                {#                        <td>{{ menu.updateAt ? menu.updateAt|date('Y-m-d H:i:s') : '' }}</td>#}
                <td>
                    <a href="{{ path('items_show', {'id': item.id}) }}" class="btn btn-outline-primary" style="width: 80px">show</a>
                    <a href="{{ path('items_edit', {'id': item.id}) }}" class="btn btn-outline-warning" style="width:80px;margin-top: -67px;margin-left:85px">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}

        </tbody>

    </table>
    <div class="navigation">

    </div>
{% endblock %}